### ISSUE TITLE
Add option to sort models alphabetically

### ISSUE THREAD

**Issue by avcordaro** [mhollink/miniature-inventory#1]
Currently the list of models in a particular group is sorted in the order you added them. Would be great to have some option to sort the models alphabetically instead, especially once you have a long list of models.

**Comment by mhollink** [comment]
I've released to version updates yesterday including sorting abilities 

Version 0.3.0 including drag and drop for custom sorting of you groups and models.
Version 0.4.0 including quick sort option to sort models on alphabetical order.

Hope this helps!
